### ISSUE TITLE
Issue with simple image

### ISSUE THREAD

**Issue by asidden** [garnele007/SwiftOCR#11]
Trying sample app for OS X to recognize attached image. It results in 'F7' as recognized string. Any ideas why this may happen ?
what are the requirements for fine recognition?
![img_2457 2](https://cloud.githubusercontent.com/assets/226486/15021510/f81b0388-122f-11e6-8838-66dd6c8b39c7.JPG)

**Comment by garnele007** [comment]
Hi, there are a few problems with this image.

1. Bright font on dark background. To recognize this image, you first have to invert it.
2. Some characters are touching each other. Currently we don't support recognition of touching characters but maybe we can add support later.
3. You shouldn't crop the image this tight. If a character is touching the border, it won't be recognized. This can be fixed by replacing `let positionIsOK = minY != 0 && minX != 0 && maxY != Int(inputImageHeight - 1) && maxX != Int(inputImageWidth - 1)` with `let positionIsOK = true`.

**Comment by asidden** [comment]
@garnele007 thanks for fast comments, will play with it

**Comment by gaetano78** [comment]
Hi, I embed your library in my project. It was quite hard because of some strange errors, so I did not import the project, but import the GPUImage and Just copy your files. I had a problem: everything works well on the iPhone simulator (the string in the test image is recognized), but doesn't work in the real device. Do you know why?

**Comment by garnele007** [comment]
@gaetano78 I don't know why is isn't working for you. If would be helpful if you could upload your project, so I can troubleshoot it. Thx
