### ISSUE TITLE
Cannot extract data from document

### ISSUE THREAD

**Issue by hoanghcmus** [garnele007/SwiftOCR#79]
I tested with many images, but it cannot extract data from the simple document or just some characters that aren't related to the image content.

----------------------------------------------------------------------------------------------
I tested with bellow image.
![test2](https://cloud.githubusercontent.com/assets/6925939/24640906/29181fe6-1925-11e7-8f8e-1458849daf69.png)
And the result is: **IT8IM00MIJ8I3CLXCIXI**

----------------------------------------------------------------------------------------------
Tested with the image: 
![test3](https://cloud.githubusercontent.com/assets/6925939/24640966/94ebe676-1925-11e7-858f-15d57f4c7c44.png)
Result is: **V**

----------------------------------------------------------------------------------------------
Tested with the image: 
![test1](https://cloud.githubusercontent.com/assets/6925939/24640974/a3c4a692-1925-11e7-9741-5b39c52c8fd2.jpg)
Nothing received.

**Comment by garnele007** [comment]
You are looking at the wrong framework for your task. SwiftOCR was designed to read short alphanumerical codes (eg. AG34DM9) and NOT to extract text from complicated images (like the second and third image).
The first image you posted can't get recognized because by default SwiftOCR can only recognize uppercase letters and numbers.
