### ISSUE TITLE
SwiftOCR direction mode

### ISSUE THREAD

**Issue by jhonny-me** [garnele007/SwiftOCR#89]
SwiftOCR works like a charm when recognizing single line numbers with a trained model.

Here comes my question:
When I have a two lines of numbers, like this:
```
12345
67890
```

SwiftOCR give me a result `1627384950` instead of `1234567890`, so I'm wondering if SwiftOCR can have some direction mode that can be configured.

And currently I split the image into two smaller image each contains only one line of number which works fine but from the result it seems SwiftOCR do have the ability to recognize multiple lines. So, guys, any idea?

**Comment by garnele007** [comment]
You can modify the sorting function `outputImages.sort(by: {return $0.0.1.origin.x < $0.1.1.origin.x})` at [Line 460](https://github.com/garnele007/SwiftOCR/blob/37fe60fbbe10c02118383545044b84db859b3675/framework/SwiftOCR/SwiftOCR.swift#L460) in the `extractBlobs` function so that the first line of numbers is sorted before the second line.
